apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: cataloguedb-deployment 
spec: 
  replicas: 1 
  selector: 
     matchLabels: 
       app: cataloguedb 
  template: 
    metadata: 
      labels: 
        app: cataloguedb 
    spec: 
      terminationGracePeriodSeconds: 30 
      hostname: cataloguedb 
      securityContext: 
        fsGroup: 10001 
      containers: 
      - name: cataloguedb 
        image: mcr.microsoft.com/mssql/server:2019-latest 
        ports: 
        - containerPort: 1433 
        env: 
        - name: MSSQL_PID 
          value: "Developer" 
        - name: ACCEPT_EULA 
          value: "Y" 
        - name: SA_PASSWORD 
          value: Test@123456 
        volumeMounts: 
        - name: mssqldb 
          mountPath: /var/opt/mssql 
      volumes: 
      - name: mssqldb 
        persistentVolumeClaim: 
          claimName: mssql-data 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: cataloguedb-deployment  
spec: 
  selector: 
    app: cataloguedb 
  ports: 
    - protocol: TCP 
      port: 1433 
      targetPort: 1433 
  type: LoadBalancer 