
apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp 
    spec:
      containers:
        - name: samplewebapp 
          image: demoappacr2.azurecr.io/demoapp:v1
          ports:
          - containerPort: 80
      


---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: samplewebapp

